import { VendorProductType, VendorType } from "@/types/vendorType";

// TODO: replace with vendor records fetched from the vendor-storefront API/database once it
// ships. Each vendor is looked up by `slug` — that's what powers the /vendor/[vendorName] route
// (see getVendorData in src/lib/data.ts) — so keep that field as the stable public identifier.
export const vendorsData: VendorType[] = [
  {
    id: 1,
    slug: "studio-craft",
    name: "Studio Craft",
    tagline: "Handcrafted Chairs & Seating",
    logo: "/images/product-details/author1.webp",
    coverImage: "/images/about/img-1.webp",
    aboutImage: "/images/welcome/img-1.webp",
    location: "Portland, USA",
    rating: 4.8,
    totalReviews: "1.2k",
    sellingSince: 2021,
    isVerified: true,
    responseTime: "Usually responds within a day",
    description:
      "Studio Craft is a small furniture workshop building solid-wood chairs the slow way — hand-joined, sanded, and finished in small batches. Every piece is designed to be repaired rather than replaced, and to look better with a decade of use than it did on day one.",
    highlights: [
      {
        title: "Handcrafted in small batches",
        description:
          "Every chair is joined and finished by hand in our Portland workshop.",
      },
      {
        title: "Sustainably sourced wood",
        description: "We work only with FSC-certified hardwood suppliers.",
      },
    ],
    social: {
      instagram: "#",
      facebook: "#",
      twitter: "#",
    },
    categories: ["Lounge Chairs", "Armchairs", "Office Chairs", "Accessories"],
  },
];

// TODO: replace with a real product API call (e.g. getProductsByVendor(vendorSlug)) filtered
// server-side by the vendor's id, rather than this embedded demo list.
export const vendorProductsData: VendorProductType[] = [
  {
    id: "sc-1",
    vendorSlug: "studio-craft",
    title: "Modern Dark Wood Lounge Chair",
    description:
      "A solid-wood lounge chair, hand-joined and finished in small batches for a decade of daily use.",
    price: 299,
    currency: "USD",
    discountPercentage: 0,
    rating: 4.8,
    totalRating: "1.2k",
    stock: 12,
    brand: "Studio Craft",
    label: "",
    category: "Lounge Chairs",
    thumbnail: "/images/home-1/top-collections/img-1.webp",
    colors: [{ code: "#4d4c4b", image: "/images/home-1/top-collections/img-1.webp" }],
    filter: "Lounge Chairs",
    images: ["/images/home-1/top-collections/img-1.webp"],
  },
  {
    id: "sc-2",
    vendorSlug: "studio-craft",
    title: "Modern Tolik Chair",
    description: "A sculptural take on the accent chair, upholstered by hand.",
    price: 199,
    currency: "USD",
    discountPercentage: 0,
    rating: 4.6,
    totalRating: "860",
    stock: 20,
    brand: "Studio Craft",
    label: "new",
    category: "Armchairs",
    thumbnail: "/images/home-1/top-collections/img-3.webp",
    colors: [{ code: "#807e7d", image: "/images/home-1/top-collections/img-3.webp" }],
    filter: "Armchairs",
    images: ["/images/home-1/top-collections/img-3.webp"],
  },
  {
    id: "sc-3",
    vendorSlug: "studio-craft",
    title: "Baxter Colette Chair",
    description: "Modern elegance meets timeless craftsmanship in solid wood.",
    price: 299,
    currency: "USD",
    discountPercentage: 0,
    rating: 4.9,
    totalRating: "540",
    stock: 8,
    brand: "Studio Craft",
    label: "new",
    category: "Armchairs",
    thumbnail: "/images/home-1/top-collections/img-5.webp",
    colors: [{ code: "#ccc9c5", image: "/images/home-1/top-collections/img-5.webp" }],
    filter: "Armchairs",
    images: ["/images/home-1/top-collections/img-5.webp"],
  },
  {
    id: "sc-4",
    vendorSlug: "studio-craft",
    title: "Cherie Lounge Chair",
    description: "A low, wide lounge chair built for long afternoons.",
    price: 199,
    currency: "USD",
    discountPercentage: 0,
    rating: 4.7,
    totalRating: "410",
    stock: 15,
    brand: "Studio Craft",
    label: "",
    category: "Lounge Chairs",
    thumbnail: "/images/home-1/top-collections/img-6.webp",
    colors: [{ code: "#1a1a19", image: "/images/home-1/top-collections/img-6.webp" }],
    filter: "Lounge Chairs",
    images: ["/images/home-1/top-collections/img-6.webp"],
  },
  {
    id: "sc-5",
    vendorSlug: "studio-craft",
    title: "Ergonomic Task Chair",
    description: "Full-day ergonomic support without sacrificing craft.",
    price: 249,
    currency: "USD",
    discountPercentage: 15,
    rating: 4.5,
    totalRating: "290",
    stock: 18,
    brand: "Studio Craft",
    label: "",
    category: "Office Chairs",
    thumbnail: "/images/home-1/featured-products/img-3.webp",
    colors: [{ code: "#4d4c4b", image: "/images/home-1/featured-products/img-3.webp" }],
    filter: "Office Chairs",
    images: ["/images/home-1/featured-products/img-3.webp"],
  },
  {
    id: "sc-6",
    vendorSlug: "studio-craft",
    title: "Woven Accent Stool",
    description: "A hand-woven rattan stool that pairs with any chair in the collection.",
    price: 149,
    currency: "USD",
    discountPercentage: 0,
    rating: 4.4,
    totalRating: "175",
    stock: 25,
    brand: "Studio Craft",
    label: "",
    category: "Accessories",
    thumbnail: "/images/home-1/top-collections/img-4.webp",
    colors: [{ code: "#807e7d", image: "/images/home-1/top-collections/img-4.webp" }],
    filter: "Accessories",
    images: ["/images/home-1/top-collections/img-4.webp"],
  },
];
